name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print repo contents for debug
        run: ls -R

      - name: Create dummy .env file (optional)
        run: |
          touch .env
          echo "SAMPLE_ENV=dev" >> .env

      - name: Build services
        run: docker compose build
